/**
 * Via Viator — Style Dictionary v4 config
 * Source: tokens/viaviator-tokens.json (DTCG: $value / $type)
 * Outputs:
 *   - src/styles/tokens.generated.css  → CSS custom properties on :root, prefix --vv-
 *   - src/lib/tokens.generated.ts      → frozen TS object for component use
 *
 * Run: npm run tokens:build  (invokes `style-dictionary build --config ...`)
 *
 * NOTE: This module registers custom format/transform on the default
 * StyleDictionary singleton (side-effect import) and exports a config
 * object — the CLI consumes the default export.
 */
import StyleDictionary from "style-dictionary";

const PREFIX = "vv";

/* ------------------------------------------------------------------ */
/* Custom TS format — flat dot-path object, frozen, typed.            */
/* ------------------------------------------------------------------ */
StyleDictionary.registerFormat({
  name: "javascript/ts-frozen",
  format: ({ dictionary }) => {
    const entries = dictionary.allTokens
      .map((t) => {
        const key = t.path.join(".");
        const raw = t.$value ?? t.value;
        const val = JSON.stringify(raw);
        const comment = t.$description ? ` /* ${t.$description} */` : "";
        return `  ${JSON.stringify(key)}: ${val} as const,${comment}`;
      })
      .join("\n");

    return [
      "/**",
      " * AUTOGENERATED by Style Dictionary — DO NOT EDIT.",
      " * Source: tokens/viaviator-tokens.json",
      ` * Generated: ${new Date().toISOString()}`,
      " */",
      "",
      "export const tokens = Object.freeze({",
      entries,
      "});",
      "",
      "export type TokenKey = keyof typeof tokens;",
      "export type TokenValue = (typeof tokens)[TokenKey];",
      "",
      "/** CSS custom-property reference, e.g. cssVar(\"color.brand.red\") → var(--vv-color-brand-red) */",
      "export function cssVar(key: TokenKey): string {",
      `  return \`var(--${PREFIX}-\${String(key).replace(/\\./g, "-")})\`;`,
      "}",
      "",
    ].join("\n");
  },
});

/* ------------------------------------------------------------------ */
/* CSS font-family transform — strip outer wrapping quotes that SD    */
/* applies to string values, leaving inner quoted family names intact.*/
/* ------------------------------------------------------------------ */
StyleDictionary.registerTransform({
  name: "css/font-family-raw",
  type: "value",
  transitive: true,
  filter: (token) => {
    const ty = token.$type ?? token.type;
    return ty === "fontFamily";
  },
  transform: (token) => {
    const v = token.$value ?? token.value;
    return typeof v === "string" ? v : String(v);
  },
});

/* ------------------------------------------------------------------ */
/* Default export = Style Dictionary config consumed by the CLI.      */
/* ------------------------------------------------------------------ */
export default {
  source: ["tokens/viaviator-tokens.json"],
  log: {
    verbosity: "default",
    warnings: "warn",
    errors: { brokenReferences: "throw" },
  },
  platforms: {
    css: {
      transformGroup: "css",
      transforms: ["attribute/cti", "name/kebab", "css/font-family-raw"],
      buildPath: "src/styles/",
      prefix: PREFIX,
      files: [
        {
          destination: "tokens.generated.css",
          format: "css/variables",
          options: {
            outputReferences: false,
            selector: ":root",
            fileHeader: () => [
              "AUTOGENERATED by Style Dictionary — DO NOT EDIT.",
              "Source: tokens/viaviator-tokens.json",
              "Run `npm run tokens:build` to regenerate.",
            ],
          },
        },
      ],
    },
    ts: {
      transformGroup: "js",
      transforms: ["attribute/cti", "name/kebab"],
      buildPath: "src/lib/",
      prefix: PREFIX,
      files: [
        {
          destination: "tokens.generated.ts",
          format: "javascript/ts-frozen",
        },
      ],
    },
  },
};
